require('dotenv').config();
const path = require('path'), fs = require('fs'), crypto = require('crypto'), nodemailer = require('nodemailer');
const express = require('express'), http = require('http'), helmet = require('helmet'), cors = require('cors'), rateLimit = require('express-rate-limit'), compression = require('compression'), bcrypt = require('bcryptjs'), jwt = require('jsonwebtoken'), multer = require('multer');
const { Server } = require('socket.io'); const db = require('./database/db'); const { sign, verify, requireAuth, requireAdmin } = require('./middleware/auth');
const app = express(), server = http.createServer(app), io = new Server(server, { cors: { origin: true, credentials: true } });
const PORT = Number(process.env.PORT || 3000), uploads = path.join(__dirname, 'uploads'); fs.mkdirSync(uploads, { recursive: true });
app.use(helmet({ contentSecurityPolicy: false })); app.use(cors({ origin: true, credentials: true })); app.use(compression()); app.use(express.json({ limit: '1mb' })); app.use(rateLimit({ windowMs: 15 * 60e3, limit: 200, standardHeaders: 'draft-7' })); app.use(express.static(path.join(__dirname, 'public')));
const cookie = (res, token) => res.cookie('token', token, { httpOnly: true, sameSite: 'lax', secure: process.env.NODE_ENV === 'production', maxAge: 30 * 864e5 });
app.post('/api/auth/register', async (req,res,next) => { try { const { name, username, email, password } = req.body; if (!name || !/^[a-zA-Z0-9_]{3,24}$/.test(username || '') || !/^\S+@\S+\.\S+$/.test(email || '') || (password || '').length < 8) return res.status(400).json({ error: 'Use a name, a 3–24 character username, a valid email, and an 8+ character password.' }); const hash = await bcrypt.hash(password, 12); const info = db.prepare('INSERT INTO users (name,username,email,password_hash) VALUES (?,?,?,?)').run(name.trim(), username.toLowerCase(), email.toLowerCase(), hash); const user = db.prepare('SELECT id,name,username,email,bio,status,is_admin AS isAdmin FROM users WHERE id=?').get(info.lastInsertRowid); cookie(res, sign(user, true)); res.status(201).json({ user }); } catch (e) { res.status(e.code?.includes('UNIQUE') ? 409 : 500).json({ error: e.code?.includes('UNIQUE') ? 'That username or email is already in use.' : 'Unable to create account.' }); } });
app.post('/api/auth/login', async (req,res) => { const { identity, password, remember } = req.body; const user = db.prepare('SELECT * FROM users WHERE email=? OR username=?').get((identity || '').toLowerCase(), (identity || '').toLowerCase()); if (!user || !await bcrypt.compare(password || '', user.password_hash)) return res.status(401).json({ error: 'Incorrect email/username or password.' }); cookie(res, sign(user, remember)); res.json({ user: { id:user.id,name:user.name,username:user.username,email:user.email,bio:user.bio,status:user.status,avatarUrl:user.avatar_url,themeColor:user.theme_color,appName:user.app_name,isAdmin:!!user.is_admin } }); });
app.post('/api/auth/logout', (req,res) => { res.clearCookie('token'); res.status(204).end(); });
app.post('/api/auth/forgot-password', async (req,res) => { const identity=(req.body.identity||'').trim().toLowerCase(); const user=db.prepare('SELECT id,name,email FROM users WHERE email=? OR username=?').get(identity,identity); if (!user) return res.json({ message:'If that account exists, a reset code will be sent.' }); if (!process.env.SMTP_HOST || !process.env.SMTP_USER || !process.env.SMTP_PASS) return res.status(503).json({ error:'Email reset is not configured yet. Ask the administrator to configure SMTP.' }); const code=crypto.randomInt(100000,1000000).toString(); const codeHash=await bcrypt.hash(code,10); const expiresAt=new Date(Date.now()+15*60e3).toISOString(); db.prepare('UPDATE password_resets SET used=1 WHERE user_id=? AND used=0').run(user.id); db.prepare('INSERT INTO password_resets (user_id,code_hash,expires_at) VALUES (?,?,?)').run(user.id,codeHash,expiresAt); try { const transport=nodemailer.createTransport({ host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:process.env.SMTP_SECURE==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS} }); await transport.sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to:user.email,subject:'Mardara password reset code',text:`Hello ${user.name}, your Mardara password reset code is ${code}. It expires in 15 minutes.`}); res.json({ message:'A 6-digit reset code has been sent to your email.' }); } catch { res.status(502).json({ error:'The reset email could not be sent. Please try again later.' }); } });
app.post('/api/auth/reset-password', async (req,res) => { const { identity,code,password }=req.body; if (typeof password!=='string'||password.length<8) return res.status(400).json({ error:'Password must be at least 8 characters.' }); const user=db.prepare('SELECT id FROM users WHERE email=? OR username=?').get((identity||'').trim().toLowerCase(),(identity||'').trim().toLowerCase()); const reset=user&&db.prepare("SELECT * FROM password_resets WHERE user_id=? AND used=0 AND expires_at > datetime('now') ORDER BY id DESC LIMIT 1").get(user.id); if (!reset || !await bcrypt.compare(code||'',reset.code_hash)) return res.status(400).json({ error:'Invalid or expired reset code.' }); db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(await bcrypt.hash(password,12),user.id); db.prepare('UPDATE password_resets SET used=1 WHERE id=?').run(reset.id); res.json({ message:'Password reset. You can now sign in.' }); });
app.get('/api/me', requireAuth, (req,res) => res.json({ user: db.prepare('SELECT id,name,username,email,bio,status,avatar_url AS avatarUrl,theme_color AS themeColor,app_name AS appName,app_identity_locked AS appIdentityLocked,is_admin AS isAdmin FROM users WHERE id=?').get(req.user.id) }));
app.get('/api/users', requireAuth, (req,res) => { const q = `%${(req.query.q || '').trim()}%`; res.json({ users: db.prepare('SELECT id,name,username,email,bio,status,avatar_url AS avatarUrl FROM users WHERE id != ? AND (name LIKE ? OR username LIKE ? OR email LIKE ?) LIMIT 30').all(req.user.id,q,q,q) }); });
app.get('/api/users/:id', requireAuth, (req,res) => { const user=db.prepare('SELECT id,name,username,bio,status,avatar_url AS avatarUrl,is_admin AS isAdmin,created_at FROM users WHERE id=?').get(Number(req.params.id)); user ? res.json({ user }) : res.status(404).json({ error:'User not found.' }); });
app.put('/api/profile', requireAuth, (req,res) => { const { name,bio,status,themeColor,appName } = req.body; const current=db.prepare('SELECT app_identity_locked FROM users WHERE id=?').get(req.user.id); const color=/^#[0-9a-fA-F]{6}$/.test(themeColor||'') ? themeColor : null, brand=typeof appName==='string'&&appName.trim() ? appName.trim().slice(0,40) : null; if (current.app_identity_locked && (color||brand)) return res.status(403).json({ error:'Your app name and color are permanent and cannot be changed again.' }); const lockIdentity=(color||brand)?1:0; db.prepare('UPDATE users SET name=COALESCE(?,name), bio=COALESCE(?,bio), status=COALESCE(?,status), theme_color=COALESCE(?,theme_color), app_name=COALESCE(?,app_name), app_identity_locked=CASE WHEN ? THEN 1 ELSE app_identity_locked END WHERE id=?').run(name?.trim() || null,bio?.trim() || null,status?.trim() || null,color,brand,lockIdentity,req.user.id); res.json({ user: db.prepare('SELECT id,name,username,email,bio,status,avatar_url AS avatarUrl,theme_color AS themeColor,app_name AS appName,app_identity_locked AS appIdentityLocked,is_admin AS isAdmin FROM users WHERE id=?').get(req.user.id) }); });
app.post('/api/meetings', requireAuth, async (req,res) => { const { title, startsAt, duration=60, password, waitingRoom=false } = req.body; if (!title?.trim()) return res.status(400).json({ error:'A meeting title is required.' }); const code = `${Math.random().toString(36).slice(2,6)}-${Math.random().toString(36).slice(2,6)}`.toUpperCase(); const pass = password ? await bcrypt.hash(password, 12) : null; db.prepare('INSERT INTO meetings (code,host_id,title,password_hash,starts_at,duration,waiting_room) VALUES (?,?,?,?,?,?,?)').run(code,req.user.id,title.trim(),pass,startsAt || null,Math.min(Math.max(+duration || 60,15),480),waitingRoom ? 1 : 0); res.status(201).json({ code, link: `${req.protocol}://${req.get('host')}/meeting/${code}` }); });
app.get('/api/meetings/:code', requireAuth, (req,res) => { const meeting = db.prepare('SELECT m.code,m.title,m.starts_at,m.duration,m.locked,m.waiting_room,u.name host_name,m.host_id FROM meetings m JOIN users u ON u.id=m.host_id WHERE m.code=?').get(req.params.code.toUpperCase()); meeting ? res.json({ meeting }) : res.status(404).json({ error:'Meeting not found.' }); });
app.get('/api/calls/history', requireAuth, (req,res) => res.json({ calls: db.prepare('SELECT c.*, u.name contact_name FROM calls c JOIN users u ON u.id=CASE WHEN c.caller_id=? THEN c.receiver_id ELSE c.caller_id END WHERE c.caller_id=? OR c.receiver_id=? ORDER BY c.started_at DESC LIMIT 50').all(req.user.id,req.user.id,req.user.id) }));
app.get('/api/admin/overview', requireAuth, requireAdmin, (req,res) => {
  const stats = db.prepare(`SELECT
    (SELECT COUNT(*) FROM users) AS users,
    (SELECT COUNT(*) FROM meetings) AS meetings,
    (SELECT COUNT(*) FROM calls) AS calls,
    (SELECT COALESCE(SUM(duration),0) FROM calls) AS callSeconds,
    (SELECT COUNT(*) FROM messages) AS messages,
    (SELECT COUNT(*) FROM notifications) AS notifications`).get();
  const users = db.prepare('SELECT id,name,username,email,status,avatar_url AS avatarUrl,is_admin AS isAdmin,created_at FROM users ORDER BY created_at DESC LIMIT 100').all();
  const calls = db.prepare(`SELECT c.*, caller.name AS caller_name, receiver.name AS receiver_name
    FROM calls c JOIN users caller ON caller.id=c.caller_id JOIN users receiver ON receiver.id=c.receiver_id
    ORDER BY c.started_at DESC LIMIT 100`).all();
  const meetings = db.prepare(`SELECT m.code,m.title,m.starts_at,m.duration,m.locked,m.waiting_room,m.created_at,u.name AS host_name
    FROM meetings m JOIN users u ON u.id=m.host_id ORDER BY m.created_at DESC LIMIT 100`).all();
  const messages = db.prepare(`SELECT msg.id,msg.body,msg.file_name,msg.file_path,msg.created_at,u.name AS sender_name,m.code AS meeting_code
    FROM messages msg JOIN users u ON u.id=msg.sender_id LEFT JOIN meetings m ON m.id=msg.meeting_id ORDER BY msg.created_at DESC LIMIT 100`).all();
  res.json({ stats, users, calls, meetings, messages });
});
const allowed = new Set(['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','image/png','image/jpeg','image/webp','application/zip']); const upload = multer({ storage: multer.diskStorage({ destination:uploads, filename:(r,f,cb)=>cb(null,`${Date.now()}-${Math.random().toString(36).slice(2)}${path.extname(f.originalname)}`) }), limits:{ fileSize:Number(process.env.MAX_FILE_SIZE || 10485760) }, fileFilter:(r,f,cb)=>cb(null,allowed.has(f.mimetype)) });
app.post('/api/uploads', requireAuth, upload.single('file'), (req,res) => req.file ? res.status(201).json({ name:req.file.originalname, path:`/uploads/${req.file.filename}` }) : res.status(400).json({ error:'Unsupported file.' })); app.use('/uploads', express.static(uploads));
app.post('/api/profile/photo', requireAuth, upload.single('photo'), (req,res) => { try { if (!req.file || !req.file.mimetype.startsWith('image/')) return res.status(400).json({ error:'Please upload a PNG, JPEG, or WebP profile photo.' }); const avatarUrl=`/uploads/${req.file.filename}`; db.prepare('UPDATE users SET avatar_url=? WHERE id=?').run(avatarUrl,req.user.id); res.status(201).json({ avatarUrl }); } catch (error) { console.error('Profile photo save failed:', error); res.status(500).json({ error:'Could not save the profile photo. Please try again.' }); } });
app.delete('/api/admin/users/:id', requireAuth, requireAdmin, (req,res) => { const userId=Number(req.params.id); if (!Number.isInteger(userId) || userId<1) return res.status(400).json({ error:'Invalid user.' }); if (userId===req.user.id) return res.status(400).json({ error:'You cannot delete your own administrator account.' }); const target=db.prepare('SELECT id FROM users WHERE id=?').get(userId); if (!target) return res.status(404).json({ error:'User not found.' }); db.exec('BEGIN'); try { db.prepare('DELETE FROM messages WHERE sender_id=? OR meeting_id IN (SELECT id FROM meetings WHERE host_id=?)').run(userId,userId); db.prepare('DELETE FROM notifications WHERE user_id=?').run(userId); db.prepare('DELETE FROM calls WHERE caller_id=? OR receiver_id=?').run(userId,userId); db.prepare('DELETE FROM meetings WHERE host_id=?').run(userId); db.prepare('DELETE FROM users WHERE id=?').run(userId); db.exec('COMMIT'); res.status(204).end(); } catch (error) { db.exec('ROLLBACK'); throw error; } });
app.post('/api/admin/users/:id/reset-password', requireAuth, requireAdmin, async (req,res) => { const userId=Number(req.params.id), { password }=req.body; if (!Number.isInteger(userId) || userId<1) return res.status(400).json({ error:'Invalid user.' }); if (typeof password!=='string' || password.length<8) return res.status(400).json({ error:'The new password must contain at least 8 characters.' }); const target=db.prepare('SELECT id FROM users WHERE id=?').get(userId); if (!target) return res.status(404).json({ error:'User not found.' }); const passwordHash=await bcrypt.hash(password,12); db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(passwordHash,userId); res.json({ message:'Password reset successfully.' }); });
app.get(['/meeting/:code','/app','/login','/register'], (req,res) => res.sendFile(path.join(__dirname,'public','index.html'))); app.use((err,req,res,next)=>{ console.error(err); if (err.code==='LIMIT_FILE_SIZE') return res.status(413).json({ error:'That file is too large. Please choose an image smaller than 10 MB.' }); if (err instanceof multer.MulterError) return res.status(400).json({ error:'The uploaded file could not be processed.' }); res.status(500).json({ error:`Upload failed: ${err.message || 'unknown server error'}` }); });
const online = new Map(); io.use((socket,next)=>{ try { const cookieToken = socket.handshake.headers.cookie?.match(/(?:^|; )token=([^;]+)/)?.[1]; socket.user=verify(socket.handshake.auth.token || cookieToken); next(); } catch { next(new Error('Unauthorized')); } }); io.on('connection', socket => { const user=socket.user; online.set(user.id,socket.id); io.emit('presence',{userId:user.id,online:true}); socket.join(`user:${user.id}`);
  socket.on('call-user', ({to,type}) => { const target=Number(to); if (!online.has(target)) return socket.emit('call-error',{message:'This user is offline.'}); const call=db.prepare('INSERT INTO calls (caller_id,receiver_id,type,status) VALUES (?,?,?,?)').run(user.id,target,type==='voice'?'voice':'video','ringing'); io.to(`user:${target}`).emit('incoming-call',{callId:call.lastInsertRowid,from:{id:user.id,name:user.name,username:user.username},type:type==='voice'?'voice':'video'}); });
  socket.on('call-response', ({callId,accepted}) => { const call=db.prepare('SELECT * FROM calls WHERE id=? AND receiver_id=?').get(callId,user.id); if(!call)return; db.prepare('UPDATE calls SET status=?, started_at=CASE WHEN ? THEN CURRENT_TIMESTAMP ELSE started_at END, ended_at=CASE WHEN ? THEN CURRENT_TIMESTAMP ELSE NULL END WHERE id=?').run(accepted?'active':'rejected',accepted?1:0,accepted?0:1,callId); io.to(`user:${call.caller_id}`).emit('call-response',{callId,accepted,from:user.id}); });
  socket.on('signal', ({to,data}) => { if(online.has(Number(to))) io.to(`user:${Number(to)}`).emit('signal',{from:user.id,data}); });
  socket.on('end-call', ({callId,to}) => { if(callId) db.prepare("UPDATE calls SET status='ended', ended_at=CURRENT_TIMESTAMP, duration=CAST((julianday('now')-julianday(started_at))*86400 AS INTEGER) WHERE id=?").run(callId); if(to) io.to(`user:${to}`).emit('call-ended',{from:user.id,callId}); });
  socket.on('join-room', ({code}) => { socket.join(`meeting:${code}`); socket.to(`meeting:${code}`).emit('participant-joined',{id:user.id,name:user.name}); socket.emit('room-peers', [...(io.sockets.adapter.rooms.get(`meeting:${code}`)||[])].filter(id=>id!==socket.id).map(id=>io.sockets.sockets.get(id)?.user).filter(Boolean)); });
  socket.on('room-signal', ({code,to,data}) => io.to(to).emit('room-signal',{from:socket.id,user,data})); socket.on('meeting-message', ({code,body,file}) => { if(!body?.trim() && !file)return; io.to(`meeting:${code}`).emit('meeting-message',{sender:user,body:body?.slice(0,2000),file,createdAt:new Date().toISOString()}); }); socket.on('disconnect',()=>{ if(online.get(user.id)===socket.id){online.delete(user.id);io.emit('presence',{userId:user.id,online:false});} }); });
server.listen(PORT,()=>console.log(`Mardara listening at http://localhost:${PORT}`));
